# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_code',
            field=models.CharField(blank=True, choices=[('FB', 'B-Code'), ('NC', 'C-Code')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(blank=True, choices=[('FB', 'B-Code'), ('NC', 'C-Code')], max_length=32),
        ),
    ]
