# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_receipt_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.Receipt'),
        ),
    ]
