# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_item_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='x_from_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='x_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='y_from_top',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='y_size',
            field=models.IntegerField(null=True),
        ),
    ]
